name: pxplayer Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        # --- نکته مهم ۱ ---
        # اگر پروژه اندروید شما در یک زیرپوشه قرار دارد، نام آن را اینجا وارد کنید.
        # اگر در ریشه اصلی است، همین './' را باقی بگذارید.
        working-directory: ./ # مثال: ./pxplayer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: pxplayer-release-unsigned
          # --- نکته مهم ۲ ---
          # اگر در بالا working-directory را تغییر دادید، باید آن را به ابتدای این مسیر هم اضافه کنید.
          path: app/build/outputs/apk/release/app-release-unsigned.apk # مثال: pxplayer/app/build/outputs/apk/release/app-release-unsigned.apk
